name: Docker

on:
  push:
    branches: [ master ]

env:
  VERSION: 22.3.0
  
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build --tag memoriaio/java-docker:${VERSION} --tag memoriaio/java-docker:latest .
          docker build --tag memoriaio/keycloak-docker:${VERSION} --tag memoriaio/keycloak-docker:latest --file keycloak.dockerfile .

      - name: Log into registry
        run: echo "${{ secrets.docker_password }}" | docker login -u ${{ secrets.docker_username }} --password-stdin

      - name: Push image
        run: |
          docker push memoriaio/java-docker:${VERSION}
          docker push memoriaio/java-docker:latest
          docker push memoriaio/keycloak-docker:${VERSION}
          docker push memoriaio/keycloak-docker:latest
