name: Docker

on:
  push:
    branches: [ master ]

env:
  JAVA_VERSION: 18
  
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
        docker build \
        --tag memoriaio/java-docker:${JAVA_VERSION} \
        --tag memoriaio/java-docker:latest .

      - name: Log into registry
        run: echo "${{ secrets.docker_password }}" | docker login -u ${{ secrets.docker_username }} --password-stdin

      - name: Push image
        run: |
          docker push memoriaio/java-docker:${JAVA_VERSION}
          docker push memoriaio/java-docker:latest
